services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.16.6
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./database/pb_data:/pb_data
      - ./database/pb_public:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
