version: '2.4'

services:
  app:
    build: .
    restart: unless-stopped
    cpus: '1.5'
    mem_limit: 800M
    pids_limit: 256
    volumes:
      - ./users.db:/app/users.db
    ports:
      - "5001:5001"
