version: '3.8'
services:
  kartinki:
    depends_on:
      - db
    restart: always
    build: ./src
    env_file: .env
    ports:
      - 9993:9993
    links:
      - db

  db:
    image: mysql
    restart: always
    env_file: .env
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
