version: '3.8'
services:
  labs:
    depends_on:
      - db
    links:
      - "db:database"
    restart: always
    build: ./src
    env_file: .env
    ports:
      - 9993:9993
  db:
    image: mysql
    restart: always
    env_file: .env
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
