services:
  nginx:
    container_name: proxy
    image: nginx:stable-alpine3.17-slim
    restart: unless-stopped
    pids_limit: 256
    mem_limit: 200M
    cpus: 0.5
    ports:
      - 1984:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - web
      - pocketbase

  web:
    container_name: web
    restart: unless-stopped
    pids_limit: 256
    mem_limit: 400M
    cpus: 1
    build:
      context: web/
    ports:
      - 3000
    volumes:
      - ./data:/data
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.16.6
    container_name: pocketbase
    restart: unless-stopped
    pids_limit: 256
    mem_limit: 400M
    cpus: 0.5
    ports:
      - 8090:8090
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --post-data 'identity=admin@admin.com&password=administrator' --no-verbose --tries=1 --spider http://localhost:8090/api/admins/auth-with-password || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - ./data:/workspaces
    environment:
      - DELETE_AFTER=20m
      - SLEEP=5m
      - DIRS=/workspaces
